# Generated by Django 2.2.9 on 2020-02-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_auto_20200131_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default='未命名管理员', max_length=16),
        ),
    ]
