# Generated by Django 2.2.9 on 2020-02-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_auto_20200201_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.CharField(default='https://cn.vuejs.org/images/logo.png', max_length=128),
        ),
    ]
