# Generated by Django 2.2.9 on 2020-02-05 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='删除标识')),
                ('data', models.CharField(max_length=1024)),
                ('username', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
