# Generated by Django 2.2.9 on 2020-02-03 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='删除标识')),
                ('name', models.CharField(max_length=32)),
                ('salary', models.CharField(max_length=32)),
                ('company_name', models.CharField(max_length=32)),
                ('experience', models.CharField(max_length=32)),
                ('education', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('responsibilities', models.TextField()),
                ('requirements', models.TextField()),
                ('features', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
