# Generated by Django 2.2.9 on 2020-02-03 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='top',
            field=models.IntegerField(default=0),
        ),
    ]
