# Generated by Django 2.2.9 on 2020-02-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_job', '0002_job_top'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='pub_user',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
