# Generated by Django 2.2.9 on 2020-01-31 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='删除标识')),
                ('name', models.CharField(max_length=32)),
                ('address', models.CharField(max_length=128)),
                ('desc', models.CharField(max_length=1024)),
                ('charge_person_name', models.CharField(max_length=16)),
                ('charge_person_phone', models.CharField(max_length=16)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_delete', models.BooleanField(choices=[(0, '未删除'), (1, '已删除')], default=0, verbose_name='删除标识')),
                ('source', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=32)),
                ('pubtime', models.DateTimeField()),
                ('picture', models.FileField(upload_to='')),
                ('type', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('keyword', models.CharField(max_length=32)),
                ('publisher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_nativeNews.Publisher')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
