# Generated by Django 2.2.9 on 2020-02-01 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nativeNews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='logo',
            field=models.CharField(default='https://cn.vuejs.org/images/logo.png', max_length=128),
        ),
    ]
