# Generated by Django 2.2.9 on 2020-02-01 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nativeNews', '0002_publisher_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='type',
            field=models.IntegerField(default=0),
        ),
    ]
