# Generated by Django 2.2.9 on 2020-02-02 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nativeNews', '0003_publisher_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='keyword',
        ),
        migrations.RemoveField(
            model_name='news',
            name='publisher',
        ),
        migrations.AddField(
            model_name='news',
            name='features',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='source',
            field=models.CharField(max_length=64),
        ),
    ]
