# Generated by Django 2.2.9 on 2020-02-02 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nativeNews', '0004_auto_20200202_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='type',
        ),
    ]
