# Generated by Django 2.2.9 on 2020-02-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nativeNews', '0006_news_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='md_content',
            field=models.TextField(null=True),
        ),
    ]
