# Generated by Django 2.2.9 on 2020-02-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nativeNews', '0007_news_md_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pub_user',
            field=models.CharField(default='佚名', max_length=16),
        ),
    ]
